---
title: "Analyzing Glider Data"
subtitle: "EOS 518"
author: '[Dominique Maucieri](https://www.dominiquemaucieri.com)'
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  pdf_document:
    toc: yes
    toc_depth: 3
---

```{r installing packages, include=FALSE}

#To clear the workspace
rm(list = ls(all = T))

#My theme
theme_DOM <- function () {
  theme_classic(base_size = 12) + 
    theme(
    panel.border = element_rect(colour = "black", fill = NA),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    axis.title = element_text(size = 14, face = "bold"),
    axis.text = element_text(size = 12, face = "plain"),
    legend.text = element_text(size = 12, face = "plain"),
    legend.title = element_text(size = 14, face = "bold")
  )
}

# install.packages("rerddap")

library("plyr")
library("rerddap")
library("dplyr")
library("ggplot2")
library("lubridate")
library("viridis")
library("scales")
library("rnaturalearth")
library("rnaturalearthdata")
library("ggspatial")
library("geosphere")
library("ncdf4")
library("gsw")
library("ggoce")
library("MASS")
library("tidyr")
library("reshape2")

```

# Just Washington Gliders

```{r getting glider_320 data, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE}

urlBase <- "https://gliders.ioos.us/erddap"
glider_320Info <- info("ce_320-20220720T1429",  url = urlBase)
glider_320 <- tabledap(glider_320Info, fields = c("longitude", "latitude", "time", "depth", "salinity", "chlorophyll", "dissolved_oxygen", "backscatter", "temperature", "density", "CDOM"), 'time>=2022-08-03 20:05:54+00:00', 'time<=2022-08-07 11:41:59+00:00', url = urlBase)

glider_320$ID <- "USA_WA_shallow"


glider_320$longitude <- as.numeric(glider_320$longitude)
glider_320$latitude <- as.numeric(glider_320$latitude)
glider_320$depth <- as.numeric(glider_320$depth)
glider_320$dissolved_oxygen <- as.numeric(glider_320$dissolved_oxygen)
glider_320$temperature <- as.numeric(glider_320$temperature)
glider_320$chlorophyll <- as.numeric(glider_320$chlorophyll)
glider_320$backscatter <- as.numeric(glider_320$backscatter)
glider_320$CDOM <- as.numeric(glider_320$CDOM)

glider_320$time <- as_datetime(glider_320$time)
glider_320$date <- as.Date(glider_320$time, format ="%Y-%m-%d")

```


```{r getting glider_383 data, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE}

urlBase <- "https://gliders.ioos.us/erddap"
glider_383Info <- info("ce_383-20220720T1508",  url = urlBase)
glider_383 <- tabledap(glider_383Info, fields = c("longitude", "latitude", "time", "depth", "salinity", "chlorophyll", "dissolved_oxygen", "backscatter", "temperature", "density", "CDOM"), 'time>=2022-08-06 00:00:00+00:00', 'time<=2022-08-11 19:54:11+00:00', url = urlBase)

glider_383$ID <- "USA_WA_deep"


glider_383$longitude <- as.numeric(glider_383$longitude)
glider_383$latitude <- as.numeric(glider_383$latitude)
glider_383$depth <- as.numeric(glider_383$depth)
glider_383$dissolved_oxygen <- as.numeric(glider_383$dissolved_oxygen)
glider_383$temperature <- as.numeric(glider_383$temperature)
glider_383$chlorophyll <- as.numeric(glider_383$chlorophyll)
glider_383$backscatter <- as.numeric(glider_383$backscatter)
glider_383$CDOM <- as.numeric(glider_383$CDOM)

glider_383$time <- as_datetime(glider_383$time)
glider_383$date <- as.Date(glider_383$time, format ="%Y-%m-%d")

```


```{r path map 320, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE}

ggplot(glider_320, aes(x=longitude, y = latitude)) +
  geom_point(aes(col = date)) +
  scale_color_viridis(name='Date', 
                      trans = "date", 
                      labels = label_date(format = "%Y-%m-%d") ) + 
  theme_DOM() + 
  labs(x ="Longitude", y="Latitude", title = "USA_WA_shallow")

```


```{r path map 383, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE}

ggplot(glider_383, aes(x=longitude, y = latitude)) +
  geom_point(aes(col = date)) +
  scale_color_viridis(name='Date', 
                      trans = "date", 
                      labels = label_date(format = "%Y-%m-%d") ) + 
  theme_DOM() + 
  ylim(c(46.75, 47.25)) + 
  labs(x ="Longitude", y="Latitude", title = "USA_WA_deep")

```

```{r map with shore, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE}

glider_WA <- rbind(glider_320, glider_383)

shore_WA <- c(-124.19208, 47.15073)

max_lat_map <- max(c(glider_WA$latitude, shore_WA[2])) + 1
min_lat_map <- min(c(glider_WA$latitude, shore_WA[2])) - 1

max_long_map <- max(c(glider_WA$longitude, shore_WA[1])) + 1
min_long_map <- min(c(glider_WA$longitude, shore_WA[1])) - 1


world <- ne_countries(scale = "medium", returnclass = "sf")

simple_map_WA <- ggplot(data = world) +
  geom_sf() +
  annotation_scale(location = "bl", width_hint = 0.5) +
  annotation_north_arrow(
    location = "tl",
    which_north = "true",
    style = north_arrow_fancy_orienteering
  ) +
  coord_sf(
    xlim = c(min_long_map, max_long_map),
    ylim = c(min_lat_map, max_lat_map)
  ) +
  theme_DOM() +
  geom_point(
    data = glider_WA,
    aes(
      x = longitude,
      y = latitude,
      color = ID
    ),
    size = 2
  ) +
  scale_color_manual(values = c("skyblue2", "blue2")) +
  labs(x = "Longitude", y = "Latitude") +
  geom_point(aes(x=shore_WA[1], y=shore_WA[2]), colour="red")
simple_map_WA

```


```{r profile quick and bad way, include = FALSE}

ggplot(glider_WA, aes(y=-depth, x= time)) +
  geom_point(aes(col = temperature)) + 
  theme_DOM() +
  scale_color_viridis() +
  facet_wrap(vars(ID), scales = "free") + 
  labs(x ="Date", y="Depth (m)")

```


```{r calc distance from shore, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE}

glider_WA$distance <- "Blank"

for(i in 1:nrow(glider_WA)){
  glider_WA$distance[i] <- distm(c(glider_WA$longitude[i], glider_WA$latitude[i]), shore_WA)
}

glider_WA$distance <- as.numeric(glider_WA$distance)

glider_WA$distance_km <- glider_WA$distance / 1000

```


```{r profile distance from shore, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE, fig.width=6, fig.height=8}

glider_WA$ID <- factor(glider_WA$ID, levels = c("USA_WA_shallow", "USA_WA_deep"))

ggplot(glider_WA, aes(y=-depth, x= distance_km)) +
  geom_point(aes(col = temperature)) + 
  theme_DOM() +
  scale_color_viridis() +
  facet_wrap(vars(ID), scales = "free_x") + 
  labs(x ="Distance from shore (km)", y="Depth (m)", color = "Temp")

```



```{r depth by temperature, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE}

glider_WA$temperature <- as.numeric(glider_WA$temperature)

ggplot(glider_WA, aes(y=-depth, x= temperature)) +
  geom_point(aes(col = date)) +
  scale_color_viridis(name='Date', 
                      trans = "date", 
                      labels = label_date(format = "%Y-%m-%d") ) + 
  theme_DOM() +
  facet_wrap(vars(ID)) + 
  labs(y ="Depth (m)", x="Temperature")

```





```{r depth by DO, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE}

glider_WA$dissolved_oxygen_2 <- glider_WA$dissolved_oxygen / 43.57

ggplot(glider_WA, aes(y=-depth, x=dissolved_oxygen)) +
  geom_point(aes(col = date)) +
  scale_color_viridis(name='Date', 
                      trans = "date", 
                      labels = label_date(format = "%Y-%m-%d") ) + 
  theme_DOM() +
  geom_vline(xintercept = 60, color = "red") +
  geom_vline(xintercept = 20, color = "red")+
  facet_wrap(vars(ID)) + 
  labs(y ="Depth", x="Dissolved Oxygen (umol/kg)") +
  scale_x_continuous(name = "Dissolved Oxygen (umol/kg)",
    sec.axis = sec_axis( trans=~./43.57, name="Dissolved Oxygen (ml/L)")
  ) 

```


# Just Canadian Gliders

```{r vancouver island map, warning=FALSE, tidy = TRUE, message=FALSE, echo=FALSE}

dfo_k999_nc <- nc_open(here::here("", "dfo_k999.nc"))

dfo_k999 <- as.data.frame(matrix(data=NA, nrow=7983, ncol=12))
colnames(dfo_k999) <- c("longitude", "latitude", "time", "depth", "salinity", "chlorophyll", "dissolved_oxygen", "backscatter", "temperature", "density", "CDOM", "ID")
dfo_k999$time <- dfo_k999_nc[["dim"]][["time"]]$vals
dfo_k999$time <- as.POSIXct(dfo_k999$time, origin = "1970-01-01T00:00:00+00:00")
dfo_k999$latitude <- ncvar_get(dfo_k999_nc, varid = c("latitude"))
dfo_k999$longitude <- ncvar_get(dfo_k999_nc, varid = c("longitude"))
dfo_k999$chlorophyll <- ncvar_get(dfo_k999_nc, varid = c("chlorophyll"))
dfo_k999$salinity <- ncvar_get(dfo_k999_nc, varid = c("salinity"))
dfo_k999$depth <- ncvar_get(dfo_k999_nc, varid = c("depth"))
dfo_k999$dissolved_oxygen <- ncvar_get(dfo_k999_nc, varid = c("oxygen_concentration"))
dfo_k999$temperature <- ncvar_get(dfo_k999_nc, varid = c("temperature"))
dfo_k999$backscatter <- ncvar_get(dfo_k999_nc, varid = c("backscatter_700"))
dfo_k999$ID <- "CAN_VI_deep"
dfo_k999$density <- ncvar_get(dfo_k999_nc, varid = c("density"))
dfo_k999$time <- as_datetime(dfo_k999$time)
dfo_k999$date <- as.Date(dfo_k999$time)
dfo_k999$chlorophyll <- as.numeric(dfo_k999$chlorophyll)
dfo_k999$backscatter <- as.numeric(dfo_k999$backscatter)
dfo_k999$CDOM <- ncvar_get(dfo_k999_nc, varid = c("cdom"))
dfo_k999$CDOM <- as.numeric(dfo_k999$CDOM)

dfo_k999 <- dfo_k999 %>%
  filter(latitude < 49)

```

```{r calc distance from shore dfo_k999, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE}

dfo_k999$distance <- "Blank"

shore_dfo_k999 <- c(-125.67295, 48.99768)

for(i in 1:nrow(dfo_k999)){
  dfo_k999$distance[i] <- distm(c(dfo_k999$longitude[i], dfo_k999$latitude[i]), shore_dfo_k999)
}

dfo_k999$distance <- as.numeric(dfo_k999$distance)

dfo_k999$distance_km <- dfo_k999$distance / 1000

dfo_k999$dissolved_oxygen_2 <- dfo_k999$dissolved_oxygen / 43.57

```


```{r vancouver island map dfo_bb046, warning=FALSE, tidy = TRUE, message=FALSE, echo=FALSE}

dfo_bb046_nc <- nc_open(here::here("", "dfo_bb046.nc"))

dfo_bb046 <- as.data.frame(matrix(data=NA, nrow=17799, ncol=12))
colnames(dfo_bb046) <- c("longitude", "latitude", "time", "depth", "salinity", "chlorophyll", "dissolved_oxygen", "backscatter", "temperature", "density", "CDOM", "ID")
dfo_bb046$time <- dfo_bb046_nc[["dim"]][["time"]]$vals
dfo_bb046$time <- as.POSIXct(dfo_bb046$time, origin = "1970-01-01T00:00:00+00:00")
dfo_bb046$latitude <- ncvar_get(dfo_bb046_nc, varid = c("latitude"))
dfo_bb046$longitude <- ncvar_get(dfo_bb046_nc, varid = c("longitude"))
dfo_bb046$chlorophyll <- ncvar_get(dfo_bb046_nc, varid = c("chlorophyll"))
dfo_bb046$salinity <- ncvar_get(dfo_bb046_nc, varid = c("salinity"))
dfo_bb046$depth <- ncvar_get(dfo_bb046_nc, varid = c("depth"))
dfo_bb046$dissolved_oxygen <- ncvar_get(dfo_bb046_nc, varid = c("oxygen_concentration"))
dfo_bb046$temperature <- ncvar_get(dfo_bb046_nc, varid = c("temperature"))
dfo_bb046$backscatter <- ncvar_get(dfo_bb046_nc, varid = c("backscatter_700"))
dfo_bb046$ID <- "CAN_QC_shallow"
dfo_bb046$density <- ncvar_get(dfo_bb046_nc, varid = c("density"))
dfo_bb046$time <- as_datetime(dfo_bb046$time)
dfo_bb046$date <- as.Date(dfo_bb046$time)
dfo_bb046$chlorophyll <- as.numeric(dfo_bb046$chlorophyll)
dfo_bb046$backscatter <- as.numeric(dfo_bb046$backscatter)
dfo_bb046$CDOM <- ncvar_get(dfo_bb046_nc, varid = c("cdom"))
dfo_bb046$CDOM <- as.numeric(dfo_bb046$CDOM)

dfo_bb046 <- dfo_bb046 %>%
  filter(longitude < -128.2671 & longitude > -129.75) %>%
  filter(temperature < 100) %>%
  filter(time >= "2022-06-16 10:21:57") %>%
  filter(depth < 300) 

```

```{r path map dfo_k999, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE}

dfo_k999 <- dfo_k999 %>%
  filter(time > "2022-08-03 20:47:38" & time < "2022-08-11 20:14:41")

ggplot(dfo_k999, aes(x=longitude, y = latitude)) +
  geom_point(aes(col = date)) +
  scale_color_viridis(name='Date', 
                      trans = "date", 
                      labels = label_date(format = "%Y-%m-%d") ) + 
  theme_DOM() + 
  labs(x ="Longitude", y="Latitude", title = "CAN_VI_deep")

```

```{r path map dfo_bb046, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE}

ggplot(dfo_bb046, aes(x=longitude, y = latitude)) +
  geom_point(aes(col = date)) +
  scale_color_viridis(name='Date', 
                      trans = "date", 
                      labels = label_date(format = "%Y-%m-%d") ) + 
  theme_DOM() + 
  labs(x ="Longitude", y="Latitude", title = "CAN_QC_shallow")

```


```{r calc distance from shore dfo_bb046, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE}

dfo_bb046$distance <- "Blank"

shore_dfo_bb046 <- c(-128.11844, 51.66574)

for(i in 1:nrow(dfo_bb046)){
  dfo_bb046$distance[i] <- distm(c(dfo_bb046$longitude[i], dfo_bb046$latitude[i]), shore_dfo_bb046)
}

dfo_bb046$distance <- as.numeric(dfo_bb046$distance)

dfo_bb046$distance_km <- dfo_bb046$distance / 1000

dfo_bb046$dissolved_oxygen_2 <- dfo_bb046$dissolved_oxygen / 43.57

```


```{r map VI, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE}

glider_VI <- rbind(dfo_bb046, dfo_k999)

max_lat_map_VI <- max(glider_VI$latitude) + 0.5
min_lat_map_VI <- min(glider_VI$latitude) - 0.5

max_long_map_VI <- max(glider_VI$longitude) + 0.25
min_long_map_VI <- min(glider_VI$longitude) - 0.25


simple_map_VI <- ggplot(data = world) +
  geom_sf() +
  annotation_scale(location = "bl", width_hint = 0.5) +
  annotation_north_arrow(
    location = "tl",
    which_north = "true",
    style = north_arrow_fancy_orienteering
  ) +
  coord_sf(
    xlim = c(min_long_map_VI, max_long_map_VI),
    ylim = c(min_lat_map_VI, max_lat_map_VI)
  ) +
  theme_DOM() +
  geom_point(
    data = glider_VI,
    aes(
      x = longitude,
      y = latitude,
    color = ID
    ),
    size = 2
  ) +
  labs(x = "Longitude", y = "Latitude")+
  scale_color_manual(values = c("chocolate1", "orangered3")) 
simple_map_VI

```




```{r save VI glider, include = FALSE}

write.csv(glider_VI, file = "glider_VI_clean.csv", row.names = FALSE)

```

# Both Canadian and Washington Gliders


```{r combinging it all, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE}

comb_glider <- rbind(glider_WA, glider_VI)
comb_glider$density <- as.numeric(comb_glider$density)

comb_glider$depth[comb_glider$depth == "NaN"] <- NA
comb_glider$salinity[comb_glider$salinity == "NaN"] <- NA
comb_glider$chlorophyll[comb_glider$chlorophyll == "NaN"] <- NA
comb_glider$dissolved_oxygen[comb_glider$dissolved_oxygen == "NaN"] <- NA
comb_glider$backscatter[comb_glider$backscatter == "NaN"] <- NA
comb_glider$temperature[comb_glider$temperature == "NaN"] <- NA
comb_glider$density[comb_glider$density == "NaN"] <- NA
comb_glider$CDOM[comb_glider$CDOM == "NaN"] <- NA
comb_glider$dissolved_oxygen_2[comb_glider$dissolved_oxygen_2 == "NaN"] <- NA

```


## Map

```{r map combined, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE}

max_lat_map_comb <- max(c(comb_glider$latitude, shore_WA[2], shore_dfo_k999[2], shore_dfo_k999[2])) + 0.25
min_lat_map_comb <- min(c(comb_glider$latitude, shore_WA[2], shore_dfo_k999[2], shore_dfo_k999[2])) - 0.25

max_long_map_comb <- max(c(comb_glider$longitude, shore_WA[1], shore_dfo_k999[1], shore_dfo_k999[1])) + 0.25
min_long_map_comb <- min(c(comb_glider$longitude, shore_WA[1], shore_dfo_k999[1], shore_dfo_k999[1])) - 0.25


simple_map_comb <- ggplot(data = world) +
  geom_sf() +
  annotation_scale(location = "bl", width_hint = 0.5) +
  annotation_north_arrow(
    location = "tl",
    which_north = "true",
    style = north_arrow_fancy_orienteering
  ) +
  coord_sf(
    xlim = c(min_long_map_comb, max_long_map_comb),
    ylim = c(min_lat_map_comb, max_lat_map_comb)
  ) +
  theme_DOM() +
  geom_point(
    data = comb_glider,
    aes(
      x = longitude,
      y = latitude,
      color = ID
    ),
    size = 2
  )+
  scale_color_manual(values = c("chocolate1", "orangered3", "skyblue2", "blue2")) +
  labs(x = "Longitude", y = "Latitude") +
  geom_point(aes(x=shore_WA[1], y=shore_WA[2]), colour="red") +
  geom_point(aes(x=shore_dfo_bb046[1], y=shore_dfo_bb046[2]), colour="red")+
  geom_point(aes(x=shore_dfo_k999[1], y=shore_dfo_k999[2]), colour="red")
simple_map_comb

```

## Vertical-cross shelf sections

```{r profile distance from shore comb, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE, fig.height=8, fig.width=6}

comb_glider$ID <- factor(comb_glider$ID, levels = c("CAN_QC_shallow", "CAN_VI_deep", "USA_WA_shallow", "USA_WA_deep"))

ggplot(comb_glider %>% drop_na(temperature), aes(y=-depth, x= distance_km)) +
  geom_point(aes(col = temperature)) + 
  theme_DOM() +
  scale_color_viridis() +
  facet_wrap(vars(ID), scales = "free_x", ncol=2) + 
  labs(x ="Distance from shore (km)", y="Depth (m)", color = "Temp (C)")

```


```{r profile distance from shore wiht salinity, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE, fig.height=8, fig.width=6}

ggplot(comb_glider %>% drop_na(salinity), aes(y=-depth, x= distance_km)) +
  geom_point(aes(col = salinity)) + 
  theme_DOM() +
  scale_color_viridis() +
  facet_wrap(vars(ID), scales = "free_x", ncol=2) + 
  labs(x ="Distance from shore (km)", y="Depth (m)", color = "Salinity (ppt)")

```



```{r profile distance from shore wiht chl, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE, fig.height=8, fig.width=6}

ggplot(comb_glider %>% drop_na(chlorophyll), aes(y=-depth, x= distance_km)) +
  geom_point(aes(col = chlorophyll)) + 
  theme_DOM() +
  scale_color_viridis() +
  facet_wrap(vars(ID), scales = "free_x", ncol=2) + 
  labs(x ="Distance from shore (km)", y="Depth (m)", color = "Chl (ug/L)")

```


```{r profile distance from shore with cdom, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE, fig.height=8, fig.width=6}

ggplot(comb_glider %>% drop_na(CDOM), aes(y=-depth, x= distance_km)) +
  geom_point(aes(col = CDOM)) + 
  theme_DOM() +
  scale_color_viridis() +
  facet_wrap(vars(ID), scales = "free_x", ncol=2) + 
  labs(x ="Distance from shore (km)", y="Depth (m)", color = "CDOM (ppb)")

```


```{r profile distance from shore wiht DO, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE, fig.height=8, fig.width=6}

ggplot(comb_glider %>% drop_na(dissolved_oxygen), aes(y=-depth, x= distance_km)) +
  geom_point(aes(col = dissolved_oxygen)) + 
  theme_DOM() +
  scale_color_viridis() +
  facet_wrap(vars(ID), scales = "free_x", ncol=2) + 
  labs(x ="Distance from shore (km)", y="Depth (m)", color="DO (umol/kg)")

```

```{r profile distance from shore wiht density, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE, fig.height=8, fig.width=6}

ggplot(comb_glider %>% drop_na(density), aes(y=-depth, x= distance_km)) +
  geom_point(aes(col = density)) + 
  theme_DOM() +
  scale_color_viridis() +
  facet_wrap(vars(ID), scales = "free_x", ncol=2) + 
  labs(x ="Distance from shore (km)", y="Depth (m)", color = "Density (kg/m3)")

```

```{r profile distance from shore with backscatter, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE, fig.height=8, fig.width=6}


ggplot(comb_glider %>% drop_na(backscatter), aes(y=-depth, x= distance_km)) +
  geom_point(aes(col = backscatter)) + 
  theme_DOM() +
  scale_color_viridis() +
  facet_wrap(vars(ID), scales = "free_x", ncol=2) + 
  labs(x ="Distance from shore (km)", y="Depth (m)", color = "Backscatter (/m)")

```

## Property-Property Plots

```{r depth by temperature comb, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE, fig.width=6}

ggplot(comb_glider, aes(y=-depth, x= temperature)) +
  geom_point(aes(col = distance_km)) +
  scale_color_viridis() + 
  theme_DOM() +
  facet_wrap(vars(ID), ncol = 2) + 
  labs(y ="Depth (m)", x="Temperature", color = "Distance (km)")

```



```{r depth by DO comb, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE, fig.width=6}

ggplot(comb_glider, aes(y=-depth, x=dissolved_oxygen)) +
  geom_point(aes(col = distance_km)) +
  scale_color_viridis()  + 
  theme_DOM() +
  geom_vline(xintercept = 60, color = "red") +
  geom_vline(xintercept = 20, color = "red")+
  facet_wrap(vars(ID), ncol = 2) + 
  labs(y ="Depth", x="Dissolved Oxygen (umol/kg)", color = "Distance (km)") +
  scale_x_continuous(name = "Dissolved Oxygen (umol/kg)",
    sec.axis = sec_axis( trans=~./43.57, name="Dissolved Oxygen (ml/L)")
  ) 

```



```{r depth by backscatter comb, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE, fig.width=6}

ggplot(comb_glider, aes(y=-depth, x=backscatter)) +
  geom_point(aes(col = distance_km)) +
  scale_color_viridis() + 
  theme_DOM()+
  facet_wrap(vars(ID), ncol = 2) + 
  labs(y ="Depth", x="Backscatter (units?)", color = "Distance (km)") 

```


```{r depth by density comb, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE, fig.width=6}



ggplot(comb_glider, aes(y=-depth, x=density)) +
  geom_point(aes(col = distance_km)) +
  scale_color_viridis() + 
  theme_DOM()+
  facet_wrap(vars(ID), ncol = 2) + 
  labs(y ="Depth", x="Density (kg/m3)", color = "Distance (km)") 

```



```{r depth by salinity comb, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE, fig.width=6}

ggplot(comb_glider, aes(y=-depth, x=salinity)) +
  geom_point(aes(col = distance_km)) +
  scale_color_viridis() + 
  theme_DOM()+
  facet_wrap(vars(ID), ncol = 2) + 
  labs(y ="Depth", x="Salinity (ppt)", color = "Distance (km)") 

```

```{r depth by chl comb, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE, fig.width=6}

ggplot(comb_glider, aes(y=-depth, x=chlorophyll)) +
  geom_point(aes(col = distance_km)) +
  scale_color_viridis() + 
  theme_DOM()+
  facet_wrap(vars(ID), ncol = 2) + 
  labs(y ="Depth", x="Chlorophyll (ug/L)", color = "Distance (km)") 

```
```{r depth by cdom comb, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE, fig.width=6}

ggplot(comb_glider, aes(y=-depth, x=CDOM)) +
  geom_point(aes(col = distance_km)) +
  scale_color_viridis() + 
  theme_DOM()+
  facet_wrap(vars(ID), ncol = 2) + 
  labs(y ="Depth", x="CDOM (units?)", color = "Distance (km)") 

```


## TS Diagrams

```{r basic TS plot, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE}

TS_plot <- ggplot(comb_glider, aes(y=temperature, x=salinity, col = ID)) +
  geom_smooth(se = FALSE) +
  theme_DOM() + 
  labs(y ="Temperature", x="Salinity (ppt)", color = "ID") +
  scale_color_manual(values = c("darkblue", "darkgreen", "darkorchid", "lightslateblue")) 

```


```{r making isopycnal contours, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE}
# 
# TS_plot <- TS_plot +  geom_isopycnal(eos ="gsw", ref_longitude=comb_glider$longitude, ref_latitude = comb_glider$latitude,
#   n_breaks = 15)

```

```{r making density contours by hand, include = FALSE}

# Data
temp_range <- seq(0, 20, 0.1)
sal_range <- seq(29, 35, 0.1)

dens <- matrix(data=NA, ncol = length(temp_range), nrow = length(sal_range))

for(j in 1:length(temp_range)){
  for(i in 1:length(sal_range)){
    dens[i,j] <- gsw_rho(sal_range[i],temp_range[j],0) - 1000
  }
}

contour(x=sal_range, y=temp_range,z=dens) 

```


```{r making spiciness contours by hand, include =FALSE}

temp_range <- seq(0, 20, 0.1)
sal_range <- seq(29, 35, 0.1)

spice <- matrix(data=NA, ncol = length(temp_range), nrow = length(sal_range))

for(j in 1:length(temp_range)){
  for(i in 1:length(sal_range)){
    spice[i,j] <- gsw_spiciness0(sal_range[i],temp_range[j])
  }
}

contour(x=sal_range, y=temp_range,z=spice) 

```


```{r combine all contours, echo=FALSE, warning=FALSE, tidy = TRUE, message=FALSE}

dens_df <- as.data.frame(dens)
colnames(dens_df) <- temp_range
dens_melt <- melt(dens_df)
colnames(dens_melt) <- c("temp", "dens")
dens_melt$sal <- sal_range
dens_melt$temp_num <- rep(temp_range, each=length(sal_range))

spice_df <- as.data.frame(spice)
colnames(spice_df) <- temp_range
spice_melt <- melt(spice_df)
colnames(spice_melt) <- c("temp", "spice")

contours_df <- cbind(dens_melt, spice_melt$spice)
colnames(contours_df) <- c("temp", "dens", "sal", "temp_num", "spice")
  
ggplot(contours_df, aes(x = sal, y = temp_num)) +
  geom_contour(aes(z = dens), col="grey", binwidth = 0.2) +
  geom_contour(aes(z = spice), col="seagreen3", binwidth = 0.5) +
  theme_DOM() +
  labs(y ="Temperature", x="Salinity (ppt)", color = "ID") +
  metR::geom_text_contour(aes(z = dens), stroke = 0.15, skip=0)+
  metR::geom_text_contour(aes(z = spice), stroke = 0.15, skip=0)+
  geom_smooth(comb_glider, mapping = aes(y=temperature, x=salinity, col = ID), se = FALSE) +
  scale_color_manual(values = c("chocolate1", "orangered3", "skyblue2", "blue2")) +
  xlim(31, 34.5) + 
  ylim(3,17)

```

### Profile Plots with contours


